name: "Allocator Application"
description: "Application form for submitting a request to receive DataCap to distribute as an Allocator in the Filecoin Plus Program"
body:
- type: markdown
  attributes:
    value: |
      # Pathway Address Modification
      To apply to become an Allocator, please fill complete the following form.  Application turn around time is typically 5 business days. 
- type: input
  attributes:
    label: Email 
    description: The email for your Organization that you wish to setup for an Allocator
  validations:
    required: true
- type: input
  attributes:
    label: Github Handle  
    description: The Github handle(s) which will be authorized on the Allocator
  validations:
    required: true
- type: dropdown
  attributes:
    label: Which Pathway is this for? 
    options:
      - Open Data Pathway
      - Enterprise Private Data Pathway
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Previous address  
    description: What is the (previous) address you wish to modify?
  validations:
    required: false






    
- type: input
  attributes:
    label: Additional Information 
    description: Any additional information you with to provide?
  validations:
    required: false

        
