name: "Application"
description: "Application form for submitting a request to receive DataCap to distribute as an Allocator in the Filecoin Plus Program." 
body:
- type: markdown
  attributes:
    value: |
      # Application to become an Allocator
      To apply to become an Allocator, please fill complete the following form.  Application turn around time is typically 5 business days. Organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. For example, if you are designing a pathway that specifically supports open public data, and another pathway exclusive to encrypted enterprise data.
- type: markdown
  attributes:
    value: |
      # Core Information
- type: input
  attributes:
    label: 1. Pathway Name  
    description: Allocator Pathway Name
  validations:
    required: true
- type: input
  attributes:
    label: 2. Organization  
    description: The name of your Organization
  validations:
    required: true
- type: input
  attributes:
    label: 3. On-chain address  
    description: The address you will use for DataCap distributions
  validations:
    required: true
- type: dropdown
  attributes:
    label: 4. Country or Region 
    description: Where is your business registered/if individual - country of residence
    options:
      - Afghanistan
      - Åland Islands
      - Albania
      - Algeria
      - American Samoa
      - Andorra
      - Angola
      - Anguilla
      - Antarctica
      - Antigua and Barbuda
      - Argentina
      - Armenia
      - Aruba
      - Australia
      - Austria
      - Azerbaijan
      - Bahamas
      - Bahrain
      - Bangladesh
      - Barbados
      - Belarus
      - Belgium
      - Belize
      - Benin
      - Bermuda
      - Bhutan
      - Bolivia
      - "Bonaire, Sint Eustatius and Saba"
      - Bosnia and Herzegovina
      - Botswana
      - Bouvet Island
      - Brazil
      - British Indian Ocean Territory
      - Brunei Darussalam
      - Bulgaria
      - Burkina Faso
      - Burundi
      - Cambodia
      - Cameroon
      - Canada
      - Cape Verde
      - Cayman Islands
      - Central African Republic
      - Chad
      - Chile
      - China
      - Christmas Island
      - Cocos (Keeling) Islands
      - Colombia
      - Comoros
      - Congo
      - "Congo, the Democratic Republic of the"
      - Cook Islands
      - Costa Rica
      - Côte d'Ivoire
      - Croatia
      - Cuba
      - Curaçao
      - Cyprus
      - Czech Republic
      - Denmark
      - Djibouti
      - Dominica
      - Dominican Republic
      - Ecuador
      - Egypt
      - El Salvador
      - Equatorial Guinea
      - Eritrea
      - Estonia
      - Ethiopia
      - Falkland Islands (Malvinas)
      - Faroe Islands
      - Fiji
      - Finland
      - France
      - French Guiana
      - French Polynesia
      - French Southern Territories
      - Gabon
      - Gambia
      - Georgia
      - Germany
      - Ghana
      - Gibraltar
      - Greece
      - Greenland
      - Grenada
      - Guadeloupe
      - Guam
      - Guatemala
      - Guernsey
      - Guinea
      - Guinea-Bissau
      - Guyana
      - Haiti
      - Heard Island and McDonald Islands
      - Holy See (Vatican City State)
      - Honduras
      - Hong Kong
      - Hungary
      - Iceland
      - India
      - Indonesia
      - "Iran, Islamic Republic of"
      - Iraq
      - Ireland
      - Isle of Man
      - Israel
      - Italy
      - Jamaica
      - Japan
      - Jersey
      - Jordan
      - Kazakhstan
      - Kenya
      - Kiribati
      - "Korea, Democratic People's Republic of"
      - "Korea, Republic of"
      - Kuwait
      - Kyrgyzstan
      - Lao People's Democratic Republic
      - Latvia
      - Lebanon
      - Lesotho
      - Liberia
      - Libya
      - Liechtenstein
      - Lithuania
      - Luxembourg
      - Macao
      - "Macedonia, the Former Yugoslav Republic of"
      - Madagascar
      - Malawi
      - Malaysia
      - Maldives
      - Mali
      - Malta
      - Marshall Islands
      - Martinique
      - Mauritania
      - Mauritius
      - Mayotte
      - Mexico
      - "Micronesia, Federated States of"
      - "Moldova, Republic of"
      - Monaco
      - Mongolia
      - Montenegro
      - Montserrat
      - Morocco
      - Mozambique
      - Myanmar
      - Namibia
      - Nauru
      - Nepal
      - Netherlands
      - New Caledonia
      - New Zealand
      - Nicaragua
      - Niger
      - Nigeria
      - Niue
      - Norfolk Island
      - Northern Mariana Islands
      - Norway
      - Oman
      - Pakistan
      - Palau
      - "Palestine, State of"
      - Panama
      - Papua New Guinea
      - Paraguay
      - Peru
      - Philippines
      - Pitcairn
      - Poland
      - Portugal
      - Puerto Rico
      - Qatar
      - Réunion
      - Romania
      - Russian Federation
      - Rwanda
      - Saint Barthélemy
      - "Saint Helena, Ascension and Tristan da Cunha"
      - Saint Kitts and Nevis
      - Saint Lucia
      - Saint Martin (French part)
      - Saint Pierre and Miquelon
      - Saint Vincent and the Grenadines
      - Samoa
      - San Marino
      - Sao Tome and Principe
      - Saudi Arabia
      - Senegal
      - Serbia
      - Seychelles
      - Sierra Leone
      - Singapore
      - Sint Maarten (Dutch part)
      - Slovakia
      - Slovenia
      - Solomon Islands
      - Somalia
      - South Africa
      - South Georgia and the South Sandwich Islands
      - South Sudan
      - Spain
      - Sri Lanka
      - Sudan
      - Suriname
      - Svalbard and Jan Mayen
      - Swaziland
      - Sweden
      - Switzerland
      - Syrian Arab Republic
      - Taiwan
      - Tajikistan
      - "Tanzania, United Republic of"
      - Thailand
      - Timor-Leste
      - Togo
      - Tokelau
      - Tonga
      - Trinidad and Tobago
      - Tunisia
      - Turkey
      - Turkmenistan
      - Turks and Caicos Islands
      - Tuvalu
      - Uganda
      - Ukraine
      - United Arab Emirates
      - United Kingdom
      - United States
      - United States Minor Outlying Islands
      - Uruguay
      - Uzbekistan
      - Vanuatu
      - "Venezuela, Bolivarian Republic of"
      - Viet Nam
      - "Virgin Islands, British"
      - "Virgin Islands, U.S."
      - Wallis and Futuna
      - Western Sahara
      - Yemen
      - Zambia
      - Zimbabwe
  validations:
    required: true
- type: dropdown
  attributes:
    label: 5. Region of Operations?
    description: Where you will provide your services
    options:
      - United States
      - South America
      - China
      - South Korea
      - Africa
      - Singapore
      - Japan
      - Oceania
      - Other
- type: dropdown
  attributes:
    label: 6. Type of Allocator
    description: Type of Allocator Multiple choice Automated, Market-based, Programmatic, Manual. If manual, please explain why and how different it is from existing allocators
    options:
      - Automated
      - Market-Based
      - Programmatic
      - Manual
- type: dropdown
  attributes:
    label: 7. Amount of DataCap requested for 12 months
    description: Initially you will only receive 5 PiBs of DataCap. After auditing, you will be able to apply for 10PiBs, then 20 PiBs etc. How much DataCap do you expect to allocate in the next 12 months? All selections in terms of PiB
    options:
      - 1-4.99
      - 5
      - 6-10
      - 10-50
      - 50-70 
      - 70-80
      - 80-100
      - 100
      - 101-200
      - 200-299
      - 300
      - 301-500
- type: input
  attributes:
    label: 8. About your Pathway 
    description: Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?
  validations:
    required: true
- type: checkboxes
  attributes:
    label: 9. Program Acknowledgement 
    description: I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, or other operating entity. I will follow the Code of Conduct [here](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md)
    options: 
      - label: "I adhere"
- type: input
  attributes:
    label: 10. Who are your target clients? 
    description: Describe how your pathway will evaluate potential clients and decide on whom to give DataCap. This is the most important question of this form, so try to give as much detail as you can
  validations:
    required: false
- type: input
  attributes:
    label: 11. Describe in as much detail as possible how you will perform due diligence on clients.
    description: Describe how your pathway will evaluate potential clients and decide on whom to give DataCap. This is the most important question of this form, so try to give as much detail as you can
  validations:
    required: false
- type: input
  attributes:
    label: 12. Please specify how many questions you'll ask, and provide a brief overview of the questions
    description: Kevin to return
  validations:
    required: false
- type: dropdown
  attributes:
    label: 13.  Will you use a 3rd-party "Know your client" (KYC) service?
    description: What client auditing will you perform?
    options:
      - (Yes)
      - (No)
- type: input
  attributes:
    label: 14. Can any client apply to your pathway, or will you be closed to only your own internal clients? eg/ bizdev or self-referral
    description: Do you require equal percentage distribution for your clients to their chosen SPs? (Multiple choice - Yes, No)
  validations:
    required: false
- type: input
  attributes:
    label: 15.  How do you plan to track the rate at which DataCap is being distributed to your clients?
    description: Allocation Tranche Schedule to clients (Numerical input)
  validations:
    required: false
- type: dropdown
  attributes:
    label: 16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmitting, or accessing of data.
    description: Initially you will only receive 5 PiBs of DataCap. After auditing, you will be able to apply for 10PiBs, then 20 PiBs etc. How much DataCap do you expect to allocate in the next 12 months? All selections in terms of PiB
    options:
      - 1-4.99
      - 5
      - 6-10
      - 10-50
      - 50-70 
      - 70-80
      - 80-100
      - 100
      - 101-200
      - 200-299
      - 300
      - 301-500








- type: dropdown
  attributes:
    label: Can you confirm that you will follow the Fil+ guidelines
    description: https://docs.filecoin.io/basics/how-storage-works/filecoin-plus
    options:
      - (Yes)
      - (No)
  validations:
    required: true
