name: "[Apply] Rolling Allocator Application"
description: "Application form for submitting a request to receive DataCap to distribute as an Allocator in the Filecoin Plus Program." 
body:
- type: markdown
  attributes:
    value: |
      # Application to become an Allocator
      To apply to become an Allocator, please fill complete the eight questions in this Github form. Once you have submitted this issue, please then complete this Airtable [Form](https://airtable.com/) to finialize the information for your Allocator application. 
      
      Once your Airtable form has been submitted, the results will be then linked and shared in this issue. Application turn around time is typically 5-7 business days. Organizations should submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. For example, if you are designing a pathway that specifically supports open public data, and another pathway exclusive to encrypted enterprise data.
- type: markdown
  attributes:
    value: |
      # Core Information
- type: input
  attributes:
    label: Allocator Pathway Name 
    description: Unique descriptive name of your allocator onboarding pathway	
  validations:
    required: true
- type: input
  attributes:
    label: Organization Name  
    description: The name of the Organization applying to become an authorized Allocator
  validations:
    required: true
- type: dropdown 
  attributes:
    label: Region of Operation
    description: Which geographic regions will you be primarily working with partners in?
    options:
      - Greater China Region
      - Asia minus Greater China Region
      - Africa
      - North America
      - South America
      - Europe
      - Australia 
      - Other
- type: input
  attributes:
    label: Existing On-Chain Address  
    description: The name of the Organization applying to become an authorized Allocator
  validations:
    required: true
- type: dropdown
  attributes:
    label: Which Pathway is this for? 
    options:
      - Open Data Pathway
      - Enterprise Private Data Pathway
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Data Owner Organization Name  
    description: Enter the Organization name which will represent and control this Allocator.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Country or Region 
    options:
      - Afghanistan
      - Åland Islands
      - Albania
      - Algeria
      - American Samoa
      - Andorra
      - Angola
      - Anguilla
      - Antarctica
      - Antigua and Barbuda
      - Argentina
      - Armenia
      - Aruba
      - Australia
      - Austria
      - Azerbaijan
      - Bahamas
      - Bahrain
      - Bangladesh
      - Barbados
      - Belarus
      - Belgium
      - Belize
      - Benin
      - Bermuda
      - Bhutan
      - Bolivia
      - "Bonaire, Sint Eustatius and Saba"
      - Bosnia and Herzegovina
      - Botswana
      - Bouvet Island
      - Brazil
      - British Indian Ocean Territory
      - Brunei Darussalam
      - Bulgaria
      - Burkina Faso
      - Burundi
      - Cambodia
      - Cameroon
      - Canada
      - Cape Verde
      - Cayman Islands
      - Central African Republic
      - Chad
      - Chile
      - China
      - Christmas Island
      - Cocos (Keeling) Islands
      - Colombia
      - Comoros
      - Congo
      - "Congo, the Democratic Republic of the"
      - Cook Islands
      - Costa Rica
      - Côte d'Ivoire
      - Croatia
      - Cuba
      - Curaçao
      - Cyprus
      - Czech Republic
      - Denmark
      - Djibouti
      - Dominica
      - Dominican Republic
      - Ecuador
      - Egypt
      - El Salvador
      - Equatorial Guinea
      - Eritrea
      - Estonia
      - Ethiopia
      - Falkland Islands (Malvinas)
      - Faroe Islands
      - Fiji
      - Finland
      - France
      - French Guiana
      - French Polynesia
      - French Southern Territories
      - Gabon
      - Gambia
      - Georgia
      - Germany
      - Ghana
      - Gibraltar
      - Greece
      - Greenland
      - Grenada
      - Guadeloupe
      - Guam
      - Guatemala
      - Guernsey
      - Guinea
      - Guinea-Bissau
      - Guyana
      - Haiti
      - Heard Island and McDonald Islands
      - Holy See (Vatican City State)
      - Honduras
      - Hong Kong
      - Hungary
      - Iceland
      - India
      - Indonesia
      - "Iran, Islamic Republic of"
      - Iraq
      - Ireland
      - Isle of Man
      - Israel
      - Italy
      - Jamaica
      - Japan
      - Jersey
      - Jordan
      - Kazakhstan
      - Kenya
      - Kiribati
      - "Korea, Democratic People's Republic of"
      - "Korea, Republic of"
      - Kuwait
      - Kyrgyzstan
      - Lao People's Democratic Republic
      - Latvia
      - Lebanon
      - Lesotho
      - Liberia
      - Libya
      - Liechtenstein
      - Lithuania
      - Luxembourg
      - Macao
      - "Macedonia, the Former Yugoslav Republic of"
      - Madagascar
      - Malawi
      - Malaysia
      - Maldives
      - Mali
      - Malta
      - Marshall Islands
      - Martinique
      - Mauritania
      - Mauritius
      - Mayotte
      - Mexico
      - "Micronesia, Federated States of"
      - "Moldova, Republic of"
      - Monaco
      - Mongolia
      - Montenegro
      - Montserrat
      - Morocco
      - Mozambique
      - Myanmar
      - Namibia
      - Nauru
      - Nepal
      - Netherlands
      - New Caledonia
      - New Zealand
      - Nicaragua
      - Niger
      - Nigeria
      - Niue
      - Norfolk Island
      - Northern Mariana Islands
      - Norway
      - Oman
      - Pakistan
      - Palau
      - "Palestine, State of"
      - Panama
      - Papua New Guinea
      - Paraguay
      - Peru
      - Philippines
      - Pitcairn
      - Poland
      - Portugal
      - Puerto Rico
      - Qatar
      - Réunion
      - Romania
      - Russian Federation
      - Rwanda
      - Saint Barthélemy
      - "Saint Helena, Ascension and Tristan da Cunha"
      - Saint Kitts and Nevis
      - Saint Lucia
      - Saint Martin (French part)
      - Saint Pierre and Miquelon
      - Saint Vincent and the Grenadines
      - Samoa
      - San Marino
      - Sao Tome and Principe
      - Saudi Arabia
      - Senegal
      - Serbia
      - Seychelles
      - Sierra Leone
      - Singapore
      - Sint Maarten (Dutch part)
      - Slovakia
      - Slovenia
      - Solomon Islands
      - Somalia
      - South Africa
      - South Georgia and the South Sandwich Islands
      - South Sudan
      - Spain
      - Sri Lanka
      - Sudan
      - Suriname
      - Svalbard and Jan Mayen
      - Swaziland
      - Sweden
      - Switzerland
      - Syrian Arab Republic
      - Taiwan
      - Tajikistan
      - "Tanzania, United Republic of"
      - Thailand
      - Timor-Leste
      - Togo
      - Tokelau
      - Tonga
      - Trinidad and Tobago
      - Tunisia
      - Turkey
      - Turkmenistan
      - Turks and Caicos Islands
      - Tuvalu
      - Uganda
      - Ukraine
      - United Arab Emirates
      - United Kingdom
      - United States
      - United States Minor Outlying Islands
      - Uruguay
      - Uzbekistan
      - Vanuatu
      - "Venezuela, Bolivarian Republic of"
      - Viet Nam
      - "Virgin Islands, British"
      - "Virgin Islands, U.S."
      - Wallis and Futuna
      - Western Sahara
      - Yemen
      - Zambia
      - Zimbabwe
  validations:
    required: true

- type: input
  attributes:
    label: Total amount of DataCap being requested
    description:   
  validations:
    required: true
- type: input
  attributes:
    label: Expected size of single dataset (one copy)
    description:   
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Number of replicas to store
    options:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Weekly allocation of DataCap requested  
    description: 
  validations:
    required: true
- type: input
  attributes:
    label: If you have previously applied or served as an Allocator/Notary, please provide the url to your past application(s)  
    description: 
  validations:
    required: true
- type: dropdown
  attributes:
    label: Data Type of Application
    options:
      - Slingshot
      - Public, Open Dataset (Research/Non-Profit)
      - Public, Open Commercial / Enterprise
      - Private Commercial / Enterprise
      - Private Non-Profit / Social impact
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: Custom multisig
    options:
      - (Yes)
      - (No)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Can you confirm that you will follow the Fil+ guidelines
    description: https://docs.filecoin.io/basics/how-storage-works/filecoin-plus
    options:
      - (Yes)
      - (No)
  validations:
    required: true
