name: "[Support] Slack account modification"
description: "Issue Template for submitting a request to modify/remove an authorized Slack Handle for your Allocator"
body:
- type: markdown
  attributes:
    value: |
      # Slack Communication Representive Modification
      To change/add a the Slack authorized for your Allocator please fill out the following form.  This will allow an authorized member to be added to [fil-plus-allocator](https://filecoinproject.slack.com/archives/C06MTBZ44P2) and speak on behalf of the organiztion.
- type: input
  attributes:
    label: Organization 
    description: The name of the Allocator Organization you are wishing to update an Authorized Github account for
  validations:
    required: true
- type: input
  attributes:
    label: Applicaiton Number  
    description: The Application number linked to your organization [JSON](https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators)
  validations:
    required: true
- type: dropdown
  attributes:
    label: Would you like to 
    options:
      - Remove an existing authorized SLACK handle
      - Modify an existing authorized SLACK handle
      - Add a new authorized SLACK handle
      - Other
- type: input
  attributes:
    label: Slack Handle  
    description: What is the handle name for the Slack account you wish to modify? (example Kevin-Foundation)
  validations:
    required: true
- type: input
  attributes:
    label: Slack ID  
    description: What is the handle ID?  (This can be found by viewing the profile in slack) (example D02KTGPJ36F)
  validations:
    required: true
- type: dropdown
  attributes:
    label: Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization? 
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: input
  attributes:
    label: Additional Information 
    description: Any additional information you with to provide?
  validations:
    required: false

        
